insert into address (street, number, cp, city, country) values ('digitalcity', 1, 1000, 'Bruxelles', 'Belgique');
insert into users (first_name, last_name, email, phone, password, address_id, birthdate, enabled) values ('Hello', 'Hola', 'string@string.com', '900-633-9958', '$2a$10$Lo15D8J1mfWZuFKLlHxxGOYfObkpDfrWIdkKTA8L0tYy12K6AJcMa', 1, '12/27/1955', FALSE);
insert into omnitheque (name, email, phone,address_id) values ('Innojam', 'fantoshin0@fema.gov', '8094595791',1);
insert into omnitheque (name, email, phone,address_id) values ('Innojam', 'fantoshin0@fema.gov', '8094595791',1);
insert into omnitheque (name, email, phone,address_id) values ('Innojam', 'fantoshin0@fema.gov', '8094595791',1);
insert into omnitheque (name, email, phone,address_id) values ('Innojam', 'fantoshin0@fema.gov', '8094595791',1);
insert into omnitheque (name, email, phone,address_id) values ('Innojam', 'fantoshin0@fema.gov', '8094595791',1);
insert into omnitheque (name, email, phone,address_id) values ('Innojam', 'fantoshin0@fema.gov', '8094595791',1);
insert into product (name, category) values ('Disconnect', 'MOVIE');
insert into product (name, category) values ('Just Ask My Children', 'MOVIE');
insert into product (name, category) values ('Salaam Cinema', 'MOVIE');
insert into product (name, category) values ('Leviathan', 'MOVIE');
insert into product (name, category) values ('Rush', 'MOVIE');
