server:
  port: <PORT>

spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/<DB-NAME>
      username: <USERNAME>
      password: <PASSWORD>
      driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/<DB-NAME>
#    username: <USERNAME>
#    password: <PASSWORD>
#    driver-class-name: com.mysql.jdbc.Driver

    mail:
      host: smtp.gmail.com
      port: 587
      username: m.hellodev@gmail.com
      password: Azerty92-
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

    jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  jwt:
    secret: "Y2nr@Svs1#Rume@v9^r$$hwTm563QpxLfdDTO$VdLLMnNRJmcQ"
    expiresAt: 30
    headerPrefix: "Bearer "
    headerKey: "Authorization"
