server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/<DB_NAME>
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  jwt:
    secret:
    expiresAt:
    headerPrefix: "Bearer "
    headerKey: "Authorization"
