server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_projet_spring_rest
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
#    datasource:
#      url: jdbc:mysql://localhost:3306/db_projet_spring_rest
#      username: root
#      password:
#      driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            client-secret:

application:
  jwt:
    secret:
    expiresAt:
    headerPrefix: "Bearer "
    headerKey: "Authorization"
