server:
  port: 8080

spring:
  datasource:
    url:
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  jwt:
    secret:
    expiresAt:
    headerPrefix: "Bearer "
    headerKey: "Authorization"
