server:
  port: <PORT>

spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/<DB-NAME>
      username: <USERNAME>
      password: <PASSWORD>
      driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/<DB-NAME>
#    username: <USERNAME>
#    password: <PASSWORD>
#    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  jwt:
    secret: <SECRET>
    expiresAt: 30
    headerPrefix: "Bearer "
    headerKey: "Authorization"
