server:
  port: 8082

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/db_projet_spring_rest
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://localhost:3306/db_projet_spring_rest
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 465 #${MAIL_PORT}
    username: m.hellodev@gmail.com #${MAIL_USERNAME}
    password:  upmztnvsidsbkkld #${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  jwt:
    secret: ${JWT_SECRET}
    expiresAt: 30
    headerPrefix: "Bearer "
    headerKey: "Authorization"

