server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_projet_spring_rest
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
#    url: jdbc:mysql://localhost:3306/db_projet_spring_rest
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password:  ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  jwt:
    secret: ${JWT_SECRET}
    expiresAt: 30
    headerPrefix: "Bearer "
    headerKey: "Authorization"

