server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_projet_spring_rest2
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  jwt:
    secret: ${JWT_SECRET:secret}
    expiresAt: 30
    headerPrefix: "Bearer "
    headerKey: "Authorization"