insert into product (name, category) values ('Disconnect', MOVIE);
insert into product (name, category) values ('Just Ask My Children', MOVIE);
insert into product (name, category) values ('Salaam Cinema', MOVIE);
insert into product (name, category) values ('Leviathan', MOVIE);
insert into product (name, category) values ('Rush', MOVIE);
insert into product (name, category) values ('Bête humaine, La', MOVIE);
insert into product (name, category) values ('Hard Target', MOVIE);
insert into product (name, category) values ('Letter, The', MOVIE);
insert into product (name, category) values ('Amati Girls, The', MOVIE);
insert into product (name, category) values ('What''s Your Number?', MOVIE);
insert into product (name, category) values ('Red Firecracker, Green Firecracker (Pao Da Shuang Deng)', MOVIE);
insert into product (name, category) values ('Floods of Fear', MOVIE);
insert into product (name, category) values ('Black Waters of Echo''s Pond, The', MOVIE);
insert into product (name, category) values ('Topper Returns', MOVIE);
insert into product (name, category) values ('Flash Gordon Conquers the Universe', MOVIE);
insert into product (name, category) values ('Lost Son, The', MOVIE);
insert into product (name, category) values ('A Mulher Invisível', MOVIE);
insert into product (name, category) values ('Samson and Delilah', MOVIE);
insert into product (name, category) values ('Mudge Boy, The', MOVIE);
insert into product (name, category) values ('Deranged', MOVIE);
